### ISSUE TITLE
Missing checkpoint folder

### ISSUE THREAD

**Issue by capriele** [AbdallaMohammed/SCSST#1]
Could you share the content of checkpoints and examples folders?

Many thanks!

**Comment by AbdallaMohammed** [comment]
Sure thing, will upload checkpoint and examples later today on google drive and let you know

**Comment by AbdallaMohammed** [comment]
I know I'm late, sorry for that

U2Net checkpoint: https://drive.google.com/file/d/1lajfgMFuFzCW_2EJuDTU_6mNhTxBaE9a/view?usp=share_link
Cloth2Segmentation checkpoint: https://github.com/levindabhi/cloth-segmentation
